[[main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

[[main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 2

[[main]]
    # Top-level menu entry
    identifier = "blogs"
    name = "Blogs"
    url = "/blogs/"
    weight = 3

[[main]]
    # Top-level menu entry
    identifier = "talks"
    name = "Talks"
    url = "/talks/"
    weight = 4

[[main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 5